// Generate the registry documents that CI publishes into the registry space:
// registry/00-schema.yaml as written, one notation document asserting every
// template in the catalog under a revision derived from its content, and
// registry/90-home.yaml, which puts the catalog on the space's home.
// Run with `npm run registry`; the output directory is generated/registry/.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadCatalog, root } from './catalog.mjs';

// A JSON string is a valid YAML double-quoted scalar, so every value is
// written that way: no value can be read as notation (a symbol, a variable,
// a URI reference) or break the document's structure.
const quote = value => JSON.stringify(value);

// `commit` is the repository commit being published. It is recorded on the
// catalog record, outside the revision, so every publish asserts it and
// the space shows which commit it was deployed from.
export function registryDocument(templates, site, commit) {
  const gallery = site.url.replace(/\/$/, '');
  const repository = site.repository.replace(/\/$/, '');
  const records = templates.map(t => ({
    slug: t.slug,
    name: t.name,
    summary: t.summary,
    description: t.description.trim(),
    features: t.features.map(f => `• ${f}`).join('\n'),
    category: t.category,
    version: t.version,
    license: t.license,
    author: t.author.name,
    entrypoint: t.entrypoint,
    compatibility: t.compatibility,
    page: `${gallery}/templates/${t.slug}/`,
    source: `${repository}/tree/${site.branch}/templates/${t.slug}`,
    preview: t.images[0].file,
  }));
  // The revision names which templates are listed and what they say, not
  // the commit that carried them: a merge that changes no template
  // publishes the same facts, so it commits nothing. A changed image needs
  // no new revision, because the template's preview fact changes with it.
  const revision = createHash('sha256').update(JSON.stringify(records)).digest('hex').slice(0, 16);
  const blocks = records.map(r => {
    const fields = Object.entries(r)
      .filter(([key]) => key !== 'preview')
      .map(([key, value]) => `  ${key}: ${quote(value)}`);
    return [
      'honky/template!:',
      `  this: id:honky-tonks/template/${r.slug}`,
      ...fields,
      `  preview: !include/asset ../../templates/${r.slug}/${r.preview}`,
      `  revision: ${quote(revision)}`,
    ].join('\n');
  });
  const catalog = [
    'honky/catalog!:',
    '  this: id:honky-tonks/catalog',
    `  revision: ${quote(revision)}`,
    `  commit: ${quote(commit)}`,
  ].join('\n');
  const header = '# Generated by scripts/registry.mjs from templates/*/template.yaml. Do not edit.\n';
  return { revision, text: header + '\n' + [...blocks, catalog].join('\n\n') + '\n' };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const templates = await loadCatalog();
  const site = JSON.parse(await readFile(path.join(root, 'site.config.json'), 'utf8'));
  const out = path.join(root, 'generated', 'registry');
  await rm(out, { recursive: true, force: true });
  await mkdir(out, { recursive: true });
  for (const file of ['00-schema.yaml', '90-home.yaml']) await cp(path.join(root, 'registry', file), path.join(out, file));
  const commit = process.env.GITHUB_SHA || execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
  const { revision, text } = registryDocument(templates, site, commit);
  await writeFile(path.join(out, '10-templates.yaml'), text);
  console.log(`Registry: ${templates.length} templates at revision ${revision}, commit ${commit.slice(0, 12)}, in ${path.relative(root, out)}/`);
}
