// Generate the registry documents that CI publishes into the registry space:
// registry/00-schema.yaml as written, the publish document saying what the
// catalog is now, and registry/90-home.yaml, which puts the catalog on the
// space's home.
// Run with `npm run registry`; the output directory is generated/registry/.
import { execFileSync } from 'node:child_process';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadCatalog, root } from './catalog.mjs';

// A JSON string is a valid YAML double-quoted scalar, so every value is
// written that way: no value can be read as notation (a symbol, a variable,
// a URI reference) or break the document's structure.
const quote = value => JSON.stringify(value);

// The publish document: the catalog as it is now, written as transient
// commands that registry/00-schema.yaml's rules reconcile the stored
// catalog with. Identities (the catalog, each entry, each file) are
// asserted directly, since a rule cannot mint an entity; re-asserting one
// is a no-op. `commit` is the origin commit being published.
export function registryDocument(templates, site, commit) {
  const gallery = site.url.replace(/\/$/, '');
  const origin = site.repository.replace(/\/$/, '');
  const blocks = [
    ['catalog!:', `  origin: ${quote(origin)}`],
    ['catalog/release!:', `  origin: ${quote(origin)}`, `  commit: ${quote(commit)}`],
  ];
  for (const t of templates) {
    const dir = `../../templates/${t.slug}`;
    blocks.push(['catalog/entry!:', `  slug: ${quote(t.slug)}`]);
    const info = {
      name: t.name,
      summary: t.summary,
      description: t.description.trim(),
      category: t.category,
      version: t.version,
      license: t.license,
      author: t.author.name,
      entrypoint: t.entrypoint,
      compatibility: t.compatibility,
      page: `${gallery}/templates/${t.slug}/`,
      source: `${origin}/tree/${site.branch}/templates/${t.slug}`,
    };
    blocks.push([
      'catalog/publish!:',
      `  origin: ${quote(origin)}`,
      `  slug: ${quote(t.slug)}`,
      ...Object.entries(info).map(([key, value]) => `  ${key}: ${quote(value)}`),
      `  preview: !include/asset ${dir}/${t.images[0].file}`,
    ]);
    for (const feature of t.features) {
      blocks.push(['catalog/publish-feature!:', `  slug: ${quote(t.slug)}`, `  feature: ${quote(feature)}`]);
    }
    // A template's notation files are published as assets, never
    // evaluated: installing the template evaluates them, into the
    // installer's own space.
    for (const file of t.files) {
      blocks.push(['catalog/file!:', `  slug: ${quote(t.slug)}`, `  path: ${quote(file.file)}`]);
      blocks.push([
        'catalog/publish-file!:',
        `  slug: ${quote(t.slug)}`,
        `  path: ${quote(file.file)}`,
        `  description: ${quote(file.description)}`,
        `  optional: ${file.optional === true}`,
        `  content: !include/asset ${dir}/${file.file}`,
      ]);
    }
  }
  const header = '# Generated by scripts/registry.mjs from templates/*/template.yaml. Do not edit.\n';
  return header + '\n' + blocks.map(lines => lines.join('\n')).join('\n\n') + '\n';
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const templates = await loadCatalog();
  const site = JSON.parse(await readFile(path.join(root, 'site.config.json'), 'utf8'));
  const out = path.join(root, 'generated', 'registry');
  await rm(out, { recursive: true, force: true });
  await mkdir(out, { recursive: true });
  for (const file of ['00-schema.yaml', '90-home.yaml']) await cp(path.join(root, 'registry', file), path.join(out, file));
  const commit = process.env.GITHUB_SHA || execFileSync('git', ['rev-parse', 'HEAD'], { cwd: root, encoding: 'utf8' }).trim();
  await writeFile(path.join(out, '10-catalog.yaml'), registryDocument(templates, site, commit));
  console.log(`Registry: ${templates.length} templates at commit ${commit.slice(0, 12)}, in ${path.relative(root, out)}/`);
}
